### ISSUE TITLE
Black Flashes with Dynamic FPS

### ISSUE THREAD

**Issue by juliand665** [Blancworks/Figura#180]
Hi! I'm the developer behind Dynamic FPS.

I recently got a report (https://github.com/juliand665/Dynamic-FPS/issues/47) of someone getting black flashes when the game is in the background (which is when Dynamic FPS reduces render speed to save resources). Someone else wrote that they experienced this in combination with Figura, so I thought I'd ask if y'all have any idea what might be causing this.

[My codebase](https://github.com/juliand665/Dynamic-FPS/tree/main/src/main/java/dynamicfps) is rather simple, thus I'd say it's probably less effort for you to find what I might be doing that's violating your assumptions than the other way around :)

If I had to guess, it looks to me like you might be clearing a framebuffer that I expect to just remain the same?

**Comment by Catboi8** [comment]
I also have this issue, I honestly just assumed it was dynamic fps saving resources

**Comment by Francy-chan** [comment]
fixed c:

**Comment by juliand665** [comment]
awesome, thanks!

**Comment by egeesin** [comment]
@Francy-chan I'm still having the issue with Figura 0.0.7 and Dynamic FPS 2.06, I might be confused about the timeline, is that fixed in the latest pre-release (0.0.8)? Here's my [latest.log](https://paste.ee/p/dwztx)

**Comment by Francy-chan** [comment]
yes, they're fixed on 0.0.8 pre-releases
0.0.7 got an delayed release, so the timeline is kinda messed-up
