### ISSUE TITLE
Figura alpha 7 causes a conflict with Satin API, causing weather to take substantially longer to render

### ISSUE THREAD

**Issue by Purrrpley** [Blancworks/Figura#196]
The latest version of Figura (alpha 7) adds a custom shader feature, which I think is what's causing it to conflict (I think that's the right word for this...) with [Satin API](https://www.curseforge.com/minecraft/mc-mods/satin-api) (a graphics library thing, I don't know exactly what it does because I don't use it directly, I was only using it because it's a dependency of [Blur](https://modrinth.com/mod/blur-fabric), which is a mod I normally use). According to a `git bisect`, it's caused by commit cc77f8a. It's still an issue as of commit de737b9 (latest commit on the 1.18 branch atm). 

The conflict causes a significant performance loss, and according to the F3 pie chart thing, it's caused by `weather`... For some reason... In vanilla 1.18:
![2022-01-23_13 30 46](https://user-images.githubusercontent.com/63091454/150662401-40995974-e099-4a84-9b48-5c14a42053bf.png)

With Figura alpha 7 and Satin API (v1.7.2) in 1.18.1 (and Fabric API v0.46.1):
![2022-01-23_13 26 16](https://user-images.githubusercontent.com/63091454/150662291-7f4063ed-5aec-45e0-bd1c-18ff1a7563ea.png)

And just to be even more confusing... If you add [Litematica (v0.10.1)](https://www.curseforge.com/minecraft/mc-mods/litematica) (and [MaLiLib (v0.11.5)](https://www.curseforge.com/minecraft/mc-mods/malilib)), `weather` goes back to normal and `malilib_renderworldlast` takes too long instead (and from my testing is a bit worse than the performance loss by `weather` without Litematica):
![2022-01-23_13 40 49](https://user-images.githubusercontent.com/63091454/150662645-2210c5c5-e8d5-4e09-bb9c-e513dfd16605.png)

I don't have any Figura models (yet, so far I've been using it to see other people's models) and I've been testing in single-player so it's not a misbehaving model doing this... This is about the limit of what I'm able to do without knowing much Java, but hopefully it's enough info to be able to reproduce it and fix it at some point. I haven't reported it to [Satin API](https://github.com/Ladysnake/Satin/issues) as a change in Figura caused this, but I can report it there too if you'd like :)

**Comment by Francy-chan** [comment]
can you try with one of the latest pre-releases? - you can find them on the official discord server
a lot of performance issues has been fixed in between alpha 7 and the current build

**Comment by Purrrpley** [comment]
Still happens in 0.0.8+rc2, which I think is the latest pre-release (I built it from commit de737b9, which is the latest commit on the 1.18 branch)... I did say this above, though I'm guessing you missed it:
> It's still an issue as of commit de737b9 (latest commit on the 1.18 branch atm).

![2022-01-23_16 49 15](https://user-images.githubusercontent.com/63091454/150666679-1d81eebf-e5e4-4d8c-aab7-5d57b964a8f5.png)

It's not a build from the Discord server (I'm not in there and would rather avoid joining Discord servers if possible, but if you really want me to I can), but as long as nothing is different between that build and what's available here on GitHub it should be the same build and so should happen on both

**Comment by Francy-chan** [comment]
> I did say this above, though I'm guessing you missed it

I got it, just couldnt reproduce on my end

> but as long as nothing is different between that build and what's available here on GitHub it should be the same build and so should happen on both

yes, both are exactly the same, no need to join the discord server then

**Comment by Rythillian** [comment]
I'm also having this problem on 0.0.8-1.18.x. Having the blur mod and figura installed lowered my fps from 600 to 70. Also can confirm I noticed the same thing about Litematica and Malilib. Spent forever trying to figure out why my fps was so low, wish I had seen this sooner.
